// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYGicOyj3E21tpU20776mAt347C8xc9ak',
    appId: '1:1907165903:web:9ccb9ad3fbee2cbcd485ba',
    messagingSenderId: '1907165903',
    projectId: 'kozmos-7a56f',
    authDomain: 'kozmos-7a56f.firebaseapp.com',
    storageBucket: 'kozmos-7a56f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYGicOyj3E21tpU20776mAt347C8xc9ak',
    appId: '1:1907165903:android:9ccb9ad3fbee2cbcd485ba',
    messagingSenderId: '1907165903',
    projectId: 'kozmos-7a56f',
    storageBucket: 'kozmos-7a56f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYGicOyj3E21tpU20776mAt347C8xc9ak',
    appId: '1:1907165903:ios:9ccb9ad3fbee2cbcd485ba',
    messagingSenderId: '1907165903',
    projectId: 'kozmos-7a56f',
    storageBucket: 'kozmos-7a56f.firebasestorage.app',
    iosBundleId: 'com.example.kozmos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYGicOyj3E21tpU20776mAt347C8xc9ak',
    appId: '1:1907165903:ios:9ccb9ad3fbee2cbcd485ba',
    messagingSenderId: '1907165903',
    projectId: 'kozmos-7a56f',
    storageBucket: 'kozmos-7a56f.firebasestorage.app',
    iosBundleId: 'com.example.kozmos',
  );
}
